### ISSUE TITLE
#1 Add Temperature Convertor

### ISSUE THREAD

**Issue by shivanidotcom** [shivanidotcom/HackCodeFest#1]
>> Create a Folder name "TempConvertor" 
>> This should be a responsive website
>> Please consider this under hacktoberfest

**Comment by programmerraja** [comment]
Can I work on this ?

**Comment by programmerraja** [comment]
Thank you i wil start the work

**Comment by shivanidotcom** [comment]
@programmerraja Please do follow me and star the repo.
