### ISSUE TITLE
Optimised Code

### ISSUE THREAD

**Issue by shivanidotcom** [shivanidotcom/HackCodeFest#10]
Write optimised code for sort 0 1 2.
>> Given an array nums with n objects colored red, white, or blue, sort them [in-place](https://en.wikipedia.org/wiki/In-place_algorithm) so that objects of the same color are adjacent, with the colors in the order red, white, and blue.

We will use the integers 0, 1, and 2 to represent the color red, white, and blue, respectively.

You must solve this problem without using the library's sort function.

**Comment by nitiSHONEEE** [comment]
Please assign me
