### ISSUE TITLE
#3 Add Restaurant Website  

### ISSUE THREAD

**Issue by shivanidotcom** [shivanidotcom/HackCodeFest#3]
>> Create a folder named "RestaurantWebsite"
>> This should be responsive website.

**Comment by raazseth** [comment]
Hey,

Can you just explain what the restaurant website should look like? And some resources like APIs to fetch data from? What is the crud request here?

**Comment by raazseth** [comment]
Would like to make something amazing, Can you assign me this project?

**Comment by shivanidotcom** [comment]
Yea sure start the work
